# Generated by Django 5.2.6 on 2025-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="عنوان نمونه کار",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات نمونه کار"
                    ),
                ),
                (
                    "resume_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="آدرس نمونه کار"
                    ),
                ),
                (
                    "resume_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="skills/resume",
                        verbose_name="عکس نمونه کار",
                    ),
                ),
                (
                    "resume_img_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="آدرس عکس نمونه کار"
                    ),
                ),
            ],
            options={
                "verbose_name": "رزومه",
                "verbose_name_plural": "رزومه ها",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="موضوع"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="skills/",
                        verbose_name="آیکون مهارت",
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="آدرس آیکون مهارت"
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, null=True, verbose_name="رنگ بدنه"),
                ),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت ها",
            },
        ),
    ]
