# Generated by Django 5.2.6 on 2025-10-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="webApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="نام اپلیکیشن")),
                (
                    "icon",
                    models.ImageField(
                        upload_to="app_icons/", verbose_name="آیکون اپلیکیشن"
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="آدرس آیکون اپلیکیشن"
                    ),
                ),
                ("color", models.CharField(max_length=7, verbose_name="رنگ اپلیکیشن")),
                (
                    "html_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="محتوای HTML اپلیکیشن"
                    ),
                ),
                (
                    "css_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="محتوای CSS اپلیکیشن"
                    ),
                ),
                (
                    "js_content",
                    models.TextField(
                        blank=True, null=True, verbose_name="محتوای JS اپلیکیشن"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اپلیکیشن"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "اپلیکیشن وب",
                "verbose_name_plural": "اپلیکیشن\u200cهای وب",
                "ordering": ["-created_at"],
            },
        ),
    ]
