# Generated by Django 5.2.6 on 2025-10-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webapp",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال/غیرفعال"),
        ),
        migrations.AlterField(
            model_name="webapp",
            name="name",
            field=models.CharField(max_length=100, verbose_name="نام اپلیکیشن"),
        ),
    ]
