# Generated by Django 5.2.6 on 2025-10-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Apps", "0002_webapp_is_active_alter_webapp_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webapp",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="app_icons/",
                verbose_name="آیکون اپلیکیشن",
            ),
        ),
    ]
